on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
  
  jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
        - name: 'TESTING GITHUB ACTION - Step 1'
          run: pwd
  
        - name: 'TESTING GITHUB ACTION - Step 2'
          run: echo youssefabdo
  