on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'TESTING GITHUB ACTION'
      run: pwd

      - name: 'TESTING GITHUB ACTION'
      run: echo youssefabdo

